import type { ReactNode } from "react";
import MenuHorizontal from "@/components/MenuHorizontal";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        tabIndex={-1} 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Adicionando o Menu Horizontal */}
        <MenuHorizontal />
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
